### ISSUE TITLE
Scoping review: resources for conducting scoping reviews 

### ISSUE THREAD

**Issue by danielibsen** [science-collective/scoping-review#10]
This is a databank for useful resources on how to conduct scoping reviews. Please add here as we go along.

This is based on the initial links provided by Hannah and additional searches.

**Key papers describing scoping reviews:** 
Arksey & O'Malley 2005: https://www.tandfonline.com/doi/abs/10.1080/1364557032000119616 

Levac, Colquhoun & OBrien 2010: https://implementationscience.biomedcentral.com/articles/10.1186/1748-5908-5-69 

Seminar from Cochrane:
https://training.cochrane.org/resource/scoping-reviews-what-they-are-and-how-you-can-do-them

**Guidelines for conducting scoping reviews**

Joanna Briggs Institute: https://jbi-global-wiki.refined.site/space/MANUAL/3283910770/Chapter+11%3A+Scoping+reviews

**Guidelines for reporting scoping reviews:**

PRISMA checklist: http://www.prisma-statement.org/Extensions/ScopingReviews 

PRISMA description paper: https://www.acpjournals.org/doi/10.7326/M18-0850 

**Scoping review of scoping reviews**

Tricco et al. 2016: https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-016-0116-4

**Comment by lwjohnst86** [comment]
For generating the bibliography, as long as we have the DOI, we can use [rcrossref](https://docs.ropensci.org/rcrossref/articles/rcrossref.html) to create it. (just a note to remind me later)
