### ISSUE TITLE
Test code

### ISSUE THREAD

**Issue by MarioGuCBMR** [science-collective/scoping-review#21]
I have been doing some tests with R libraries such as easyPubMed or rscopus. It would be interesting to have a folder where we could put our code so that people can glance it over and help. What are your thoughts on the best way of doing this?

**Comment by lwjohnst86** [comment]
Put any R code into the R folder on this repo. So you would git clone this repo (or in R with `usethis::create_from_github("science-collective/scoping-review")`). You'd probably need to do a few other things but that's the first step. This type of information is actually a perfect place to put in the CONTRIBUTING guidelines! I will do that today.
