### ISSUE TITLE
Please review protocol

### ISSUE THREAD

**Issue by lwjohnst86** [science-collective/scoping-review#29]
@hchats and @MarioGuCBMR please review the protocol at https://github.com/science-collective/scoping-review/blob/main/doc/protocol.Rmd

Everyone else please add your institutions to the metadata at the top.

**Comment by lwjohnst86** [comment]
Regarding authorship listing, I suggest we do it alphabetical.

**Comment by danielibsen** [comment]
Thanks Luke. I think SDCA for me is fine here. I am also okay with alphabetically re authorship.

**Comment by hchats** [comment]
Thanks, @lwjohnst86. Created a pull request to make some last minute changes to the protocol. Looks great! I am in agreement about authorship.
