### ISSUE TITLE
Issues with batch_pubmed_download and make_df_from_pubmed functions

### ISSUE THREAD

**Issue by MarioGuCBMR** [science-collective/scoping-review#34]
Hi all,

Since last month I have been unable to run pubmed-search.R. For some reason, make_df_from_pubmed() function generates an empty dataframe. Last month I figured out that this is solved when the encoding is not specified in batch_pubmed_download() function. It is possible that this is just an issue with how my computer handles these issues, but please check it out just in case.

My current function looks like this:

```
pubmed_search <-
  batch_pubmed_download(
    pubmed_query_string = search_terms$pubmed,
    dest_file_prefix = "open_collab_"
  )

```

**Comment by lwjohnst86** [comment]
hmmm, that's interesting. Ok, thanks for looking into that and figuring it out! You are using Windows or Mac or Linux?

**Comment by MarioGuCBMR** [comment]
I am currently using my windows laptop! Will try on linux next, maybe that will solve the issue :)

**Comment by danielibsen** [comment]
Have this issued been resolved? I just tried to re-run the code on my computer and it worked. Happy to look more into it if it still doesnt work.
