### ISSUE TITLE
Include the STROBE checklist as a file, maybe issue too?

### ISSUE THREAD

**Issue by lwjohnst86** [science-collective/scoping-review#36]

**Comment by danielibsen** [comment]
Why did we want to do this? We are doing a scoping review and have the relevant PRISMA checklist for that. I guess this have come up in a discussion. If not relevant, maybe we can just close this issue :)

**Comment by lwjohnst86** [comment]
Hmm, good point, I don't remember why I made this issue. Maybe for another checklist? Well, if it comes up later, we'll revisit. Closing
