### ISSUE TITLE
Write script that filters out irrelevant titles

### ISSUE THREAD

**Issue by hchats** [science-collective/scoping-review#56]
To automate exclusions at the title level

**Comment by hchats** [comment]
@lwjohnst86 As discussed on Friday, I have been looking into this. I have not written any code yet, but I have put together a provisional list:

- "Open Access" / "Open-Access"
- "Open surgery" as well  as "open" and "surgery" separated by only 2-3 words
- "Opening" (with no other mention of "open")
- "Open-label" (particularly necessary for PubMed, wherein 240 out of 947 records were randomized control trials)
- "Open Government" / "Open Governance"

**Comment by lwjohnst86** [comment]
Closing based on #62

**Comment by lwjohnst86** [comment]
Adding more exclusions can be done in the `R/exclusions.R` script :grin:
