### ISSUE TITLE
Split out all Covid records, since some might be relevant?

### ISSUE THREAD

**Issue by lwjohnst86** [science-collective/scoping-review#67]
And have as its own section in the paper or something?

There's a lot of irrelevant stuff with covid, but some is very relevant....

**Comment by MarioGuCBMR** [comment]
Let's do a first round without COVID and maybe later add a COVID one! Maybe it is a second paper...

**Comment by lwjohnst86** [comment]
I think covid cases were removed naturally from the other exclusions.
