### ISSUE TITLE
Check out initial resources to derive search terms and potential contacts

### ISSUE THREAD

**Issue by hchats** [science-collective/scoping-review#9]
Prof Bouter suggested that we contact the key people at the following organizations:
- https://www.ukrn.org/
- https://reproducibilitea.org/
- https://www.openscience.nl/en/open-science-communities

Prof Bouter suggested the following articles as a starting point:
- https://doi.org/10.12688/f1000research.74831.1 
- https://doi.org/10.1093/scipol/scab039
- https://doi.org/10.1371/journal.pbio.3000246

**Comment by hchats** [comment]
@lwjohnst86 @danielibsen @MarioGuCBMR Forgot to tag you in! I'm just emailing each of the suggested organizations to get the ball rolling :)

**Comment by danielibsen** [comment]
Great @hchats. There should be enough time until our next working day for me to go through the links and papers.
